In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.read_csv("/content/student_performance_dirty.csv")
df.head()

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
0,104387,Male,3.39,70.46,80.09,75.54,53.07,50.31,No,No,High School,4.05,65.5545,C
1,100868,Male,8.32,92.47,70.57,86.64,40.07,97.34,Yes,No,PhD,4.30,68.7795,C
2,100275,Female,3.05,69.16,97.44,30.59,95.18,50.01,No,No,Master,8.67,72.3655,B
3,104450,Female,5.04,63.04,59.75,31.27,75.25,50.62,Yes,Yes,PhD,4.68,57.4710,C
4,102578,Female,9.25,44.03,67.27,48.61,77.40,26.10,Yes,Yes,High School,8.16,59.7095,C

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5079 entries, 0 to 5078
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             5079 non-null   int64
 1   gender                 5079 non-null   object
 2   study_hours_per_day    5054 non-null   float64
 3   attendance_percentage  5055 non-null   float64
 4   assignment_score       5060 non-null   float64
 5   midterm_score          5053 non-null   float64
 6   final_exam_score       5054 non-null   float64
 7   participation_score    5079 non-null   float64
 8   internet_access        5079 non-null   object
 9   extra_classes          5079 non-null   object
 10  parent_education       5057 non-null   object
 11  sleep_hours            5063 non-null   float64
 12  overall_score          5079 non-null   float64
 13  grade                  5060 non-null   object
dtypes: float64(8), int64(1), object(5)
memory usage: 555.6+ KB

In [47]:
df.describe()

,student_id,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,sleep_hours,overall_score
count,5079.000000,5054.000000,5055.000000,5060.000000,5053.000000,5054.000000,5079.000000,5063.000000,5079.000000
mean,102499.662335,5.419438,70.468350,64.417028,62.252365,64.630421,55.133392,6.529704,63.628155
std,1445.861817,2.571262,17.283794,19.900893,21.725489,20.253860,25.961538,1.446259,10.259349
min,100000.000000,1.000000,40.020000,30.010000,25.010000,30.010000,10.000000,4.000000,33.263500
25%,101245.500000,3.220000,55.740000,47.415000,43.450000,46.860000,33.135000,5.270000,56.274250
50%,102503.000000,5.370000,70.710000,64.410000,62.340000,64.665000,55.240000,6.550000,63.522500
75%,103750.500000,7.600000,85.070000,81.247500,80.990000,82.330000,77.850000,7.800000,71.044250
max,104998.000000,10.000000,100.000000,99.980000,99.950000,100.000000,99.990000,9.000000,93.415000

In [48]:
df.shape

(5079, 14)

In [49]:
df.isnull().sum()

student_id                0
gender                    0
study_hours_per_day      25
attendance_percentage    24
assignment_score         19
midterm_score            26
final_exam_score         25
participation_score       0
internet_access           0
extra_classes             0
parent_education         22
sleep_hours              16
overall_score             0
grade                    19
dtype: int64

In [50]:
df = df.dropna()

In [51]:
df.duplicated().sum()

np.int64(78)

In [52]:
df.drop_duplicates(inplace=True)

In [53]:
df.dtypes

student_id                 int64
gender                    object
study_hours_per_day      float64
attendance_percentage    float64
assignment_score         float64
midterm_score            float64
final_exam_score         float64
participation_score      float64
internet_access           object
extra_classes             object
parent_education          object
sleep_hours              float64
overall_score            float64
grade                     object
dtype: object

In [54]:
df['study_hours_per_day'] = df['study_hours_per_day'].astype(int)

In [55]:
df['sleep_hours'] = df['sleep_hours'].astype(int)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4829 entries, 0 to 5078
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             4829 non-null   int64
 1   gender                 4829 non-null   object
 2   study_hours_per_day    4829 non-null   int64
 3   attendance_percentage  4829 non-null   float64
 4   assignment_score       4829 non-null   float64
 5   midterm_score          4829 non-null   float64
 6   final_exam_score       4829 non-null   float64
 7   participation_score    4829 non-null   float64
 8   internet_access        4829 non-null   object
 9   extra_classes          4829 non-null   object
 10  parent_education       4829 non-null   object
 11  sleep_hours            4829 non-null   int64
 12  overall_score          4829 non-null   float64
 13  grade                  4829 non-null   object
dtypes: float64(6), int64(3), object(5)
memory usage: 565.9+ KB

In [57]:
df.isnull().sum()

student_id               0
gender                   0
study_hours_per_day      0
attendance_percentage    0
assignment_score         0
midterm_score            0
final_exam_score         0
participation_score      0
internet_access          0
extra_classes            0
parent_education         0
sleep_hours              0
overall_score            0
grade                    0
dtype: int64

In [58]:
df.duplicated().sum()

np.int64(0)

In [59]:
df.to_csv("cleaned_data.csv", index=False)

In [60]:
from google.colab import files
files.download("cleaned_data.csv")